export const SAMPLE_RIDES = [
  {
    id: "demo-ride-1",
    rideType: "carpool",
    origin: { name: "Astarang Bus Stand", lat: 19.9735, lng: 86.2716 },
    destination: { name: "Bhubaneswar Railway Station", lat: 20.2647, lng: 85.8431 },
    departureTime: "2026-10-08T07:30:00+05:30",
    seatsTotal: 4,
    seatsAvailable: 2,
    pricePerSeat: 299,
    distanceKm: 78,
    durationMinutes: 125,
    vehicle: { make: "Maruti", model: "Ertiga", color: "White", plateNumber: "OD-02-AX-4821" },
    driver: { id: "driver-1", fullName: "Rakesh Kumar", rating: 4.9, trips: 128, verified: true },
    status: "scheduled",
    allowLuggage: true,
    womenOnly: false,
    notes: "One tea stop on the way. Small luggage is welcome.",
  },
  {
    id: "demo-ride-2",
    rideType: "carpool",
    origin: { name: "Puri Railway Station", lat: 19.8072, lng: 85.8383 },
    destination: { name: "Patia, Bhubaneswar", lat: 20.3549, lng: 85.8277 },
    departureTime: "2026-10-08T09:15:00+05:30",
    seatsTotal: 3,
    seatsAvailable: 3,
    pricePerSeat: 249,
    distanceKm: 66,
    durationMinutes: 105,
    vehicle: { make: "Tata", model: "Nexon", color: "Blue", plateNumber: "OD-13-Q-9012" },
    driver: { id: "driver-2", fullName: "Meena Das", rating: 4.8, trips: 94, verified: true },
    status: "scheduled",
    allowLuggage: false,
    womenOnly: true,
    notes: "Women-only ride. Pickup is at the main station gate.",
  },
  {
    id: "demo-ride-3",
    rideType: "private",
    origin: { name: "Bhubaneswar", lat: 20.2961, lng: 85.8245 },
    destination: { name: "Konark Sun Temple", lat: 19.8876, lng: 86.0945 },
    departureTime: "2026-10-09T10:00:00+05:30",
    seatsTotal: 6,
    seatsAvailable: 6,
    estimatedFare: 2199,
    distanceKm: 65,
    durationMinutes: 110,
    vehicle: { make: "Toyota", model: "Innova Crysta", color: "Silver", plateNumber: "OD-02-BZ-7730" },
    driver: { id: "driver-3", fullName: "Sanjay Behera", rating: 4.7, trips: 76, verified: true },
    status: "scheduled",
    allowLuggage: true,
    notes: "Full-car booking with AC. Two comfort stops available.",
  },
  {
    id: "demo-ride-live",
    rideType: "on_demand",
    origin: { name: "Jaydev Vihar", lat: 20.3008, lng: 85.8191 },
    destination: { name: "Biju Patnaik International Airport", lat: 20.2444, lng: 85.8178 },
    departureTime: "2026-10-07T15:15:00+05:30",
    seatsTotal: 4,
    seatsAvailable: 3,
    estimatedFare: 349,
    distanceKm: 9.2,
    durationMinutes: 28,
    vehicle: { make: "Hyundai", model: "Aura", color: "White", plateNumber: "OD-02-CC-1428" },
    driver: { id: "driver-4", fullName: "Bikash Rout", rating: 4.9, trips: 211, verified: true },
    status: "in_progress",
    currentLocation: { lat: 20.281, lng: 85.8185, heading: 179 },
    allowLuggage: true,
    notes: "Live demo trip.",
  },
];

export const SAMPLE_GROUPS = [
  {
    id: "demo-group-1",
    name: "Puri Morning Commuters",
    description: "Share regular weekday rides between Astarang and Puri.",
    origin: { name: "Astarang", lat: 19.9735, lng: 86.2716 },
    destination: { name: "Puri", lat: 19.8135, lng: 85.8312 },
    departureDate: "2026-10-10",
    preferredTime: "07:00",
    memberCount: 8,
    maxMembers: 12,
    isMember: true,
    messages: [
      { id: "m1", senderName: "Anita", message: "Can we meet near the bus stand at 6:50?", createdAt: "2026-10-07T09:12:00+05:30" },
      { id: "m2", senderName: "Rakesh", message: "Works for me. I can offer three seats.", createdAt: "2026-10-07T09:18:00+05:30" },
    ],
  },
  {
    id: "demo-group-2",
    name: "Bhubaneswar Office Pool",
    description: "Daily office commuters. Quiet rides and punctual pickup.",
    origin: { name: "Cuttack", lat: 20.4625, lng: 85.883 },
    destination: { name: "Infocity, Bhubaneswar", lat: 20.352, lng: 85.816 },
    departureDate: "2026-10-12",
    preferredTime: "08:15",
    memberCount: 5,
    maxMembers: 8,
    isMember: false,
    messages: [],
  },
  {
    id: "demo-group-3",
    name: "Konark Weekend Crew",
    description: "A relaxed weekend group for beach and temple trips.",
    origin: { name: "Bhubaneswar", lat: 20.2961, lng: 85.8245 },
    destination: { name: "Konark", lat: 19.8876, lng: 86.0945 },
    departureDate: "2026-10-18",
    preferredTime: "06:30",
    memberCount: 6,
    maxMembers: 10,
    isMember: false,
    messages: [],
  },
];
